tablegen: relax a restriction of logic or
GPUOpen-Drivers/llvm-dialects pull request #62
Opened 2023-08-05 20:31 UTC by nhaehnle

(this PR also contains a cmake change in a separate commit)

The constraint system evaluator refuses to evaluate a logic or unless
all variables that appear in it have been resolved. This is a good
thing, because we can't reliably capture variables from inside a logic
or.

However, the check was too restrictive since it also refused to evaluate
a logic or that contain a local/internal variable that is introduced
purely as a connective between "apply" constraints that appear as nested
tablegen DAGs.

We relax this restriction by making the distinction between "global" and
"non-global" variables explicit.

2023-08-07 08:23 UTC, tsymalla requested changes

2023-08-07 08:23 UTC, tsymalla commented on lib/TableGen/Constraints.cpp
> +      if (self && dag->getNumArgs()) {
`!dag->arg_empty()` ?

2023-08-07 18:52 UTC, tsymalla commented
LGTM

2023-08-08 06:58 UTC, tsymalla-AMD approved these changes

2023-08-08 11:47 UTC, merged